# Generated by Django 5.0.2 on 2025-09-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generatedassignment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='ai_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
