# Generated by Django 5.0.2 on 2025-09-22 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classgroup_assignmentshare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignmentshare',
            constraint=models.UniqueConstraint(condition=models.Q(('generated_assignment__isnull', False), ('revoked_at__isnull', True)), fields=('class_group', 'generated_assignment'), name='unique_active_generated_share'),
        ),
        migrations.AddConstraint(
            model_name='assignmentshare',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('uploaded_document__isnull', False)), fields=('class_group', 'uploaded_document'), name='unique_active_uploaded_share'),
        ),
    ]
