# Generated by Django 5.0.2 on 2025-10-22 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='selected_subject',
        ),
        migrations.AddField(
            model_name='usagequota',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_board', models.CharField(choices=[('Cambridge', 'Cambridge International'), ('Edexcel', 'Edexcel'), ('GED', 'GED'), ('CAPS', 'CAPS (South Africa)'), ('IEB', 'IEB (South Africa)'), ('ZIMSEC', 'ZIMSEC (Zimbabwe)'), ('NSSC', 'Namibia Senior Secondary Certificate'), ('ZEC', 'Zambia Examinations Council'), ('other', 'Other (Specify in notes)')], max_length=50)),
                ('exam_board_custom', models.CharField(blank=True, max_length=100)),
                ('paper_type', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2'), ('paper3', 'Paper 3'), ('practical', 'Practical'), ('coursework', 'Coursework')], max_length=20)),
                ('paper_code', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='past_papers/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'subject', 'grade'],
                'unique_together': {('exam_board', 'paper_code', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_board', models.CharField(choices=[('Cambridge', 'Cambridge International'), ('Edexcel', 'Edexcel'), ('GED', 'GED'), ('CAPS', 'CAPS (South Africa)'), ('IEB', 'IEB (South Africa)'), ('ZIMSEC', 'ZIMSEC (Zimbabwe)'), ('NSSC', 'Namibia Senior Secondary Certificate'), ('ZEC', 'Zambia Examinations Council'), ('other', 'Other (Specify in notes)')], max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('google_form_link', models.URLField()),
                ('is_premium', models.BooleanField(default=False)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_from_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pastpaper')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=200)),
                ('answers_json', models.JSONField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.quiz')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscribedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subscribed_at'],
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
