# Generated by Django 5.0.2 on 2025-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usersubscription_selected_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='type',
            field=models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('classwork', 'Classwork'), ('homework', 'Homework'), ('assignment', 'Assignment'), ('test', 'Test'), ('exam', 'Exam'), ('general', 'General Document')], default='general', max_length=20),
        ),
    ]
