# Generated by Django 5.0.2 on 2025-10-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_uploadeddocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examboard',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
    ]
