# Generated by Django 5.0.2 on 2025-10-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_examboard_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('content_manager', 'Content Manager'), ('admin', 'Admin')], default='teacher', max_length=20),
        ),
    ]
