# Generated by Django 5.0.2 on 2025-10-22 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormattedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('exam_board', models.CharField(choices=[('Cambridge', 'Cambridge International'), ('Edexcel', 'Edexcel'), ('GED', 'GED'), ('CAPS', 'CAPS (South Africa)'), ('IEB', 'IEB (South Africa)'), ('ZIMSEC', 'ZIMSEC (Zimbabwe)'), ('NSSC', 'Namibia Senior Secondary Certificate'), ('ZEC', 'Zambia Examinations Council'), ('other', 'Other (Specify in notes)')], max_length=50)),
                ('year', models.IntegerField()),
                ('questions_json', models.JSONField()),
                ('memo_json', models.JSONField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('structured', 'Structured'), ('free_response', 'Free Response'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('source_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatted_versions', to='core.pastpaper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'grade', 'exam_board'], name='core_format_subject_85f050_idx'), models.Index(fields=['processing_status'], name='core_format_process_99a756_idx'), models.Index(fields=['is_published'], name='core_format_is_publ_663f8c_idx')],
            },
        ),
    ]
