# Generated by Django 5.0.2 on 2025-10-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_formattedpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='formattedpaper',
            name='has_extracted_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formattedpaper',
            name='images_directory',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
