# Generated by Django 5.0.2 on 2025-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_announcement_emailblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
