# Generated by Django 5.0.2 on 2025-11-22 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_flashcard_interactivequestion_exampaper_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(help_text='e.g., Cambridge, Edexcel, CAPS', max_length=100)),
                ('subject_code', models.CharField(help_text='e.g., 0580, 9MA0, PHYS-01', max_length=50)),
                ('subject_name', models.CharField(blank=True, help_text='e.g., Mathematics, Physics', max_length=200)),
                ('module_code', models.CharField(blank=True, help_text='Optional module/component code', max_length=50)),
                ('year', models.IntegerField(help_text='e.g., 2023')),
                ('session', models.CharField(choices=[('june', 'June'), ('november', 'November'), ('may', 'May/June'), ('february', 'February/March'), ('october', 'October/November'), ('summer', 'Summer'), ('winter', 'Winter'), ('other', 'Other')], max_length=20)),
                ('paper_number', models.CharField(help_text='e.g., 1, 2, 3, 4H, 1F', max_length=20)),
                ('variant', models.CharField(blank=True, help_text='e.g., 1, 2, 3 for Cambridge variants', max_length=10)),
                ('paper_type', models.CharField(choices=[('qp', 'Question Paper'), ('ms', 'Marking Scheme'), ('er', 'Examiner Report'), ('gt', 'Grade Thresholds'), ('ir', 'Insert/Resource Booklet'), ('specimen', 'Specimen Paper'), ('other', 'Other')], default='qp', max_length=20)),
                ('original_filename', models.CharField(help_text='Original file name for reference', max_length=255)),
                ('file', models.FileField(upload_to='official_exam_papers/%Y/%m/')),
                ('folder_path', models.CharField(help_text='Relative path from upload root', max_length=500)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional parsed metadata')),
                ('is_public', models.BooleanField(default=True, help_text='Visible on public download page')),
                ('can_use_for_training', models.BooleanField(default=True, help_text='Use for AI training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'board', 'subject_code', 'session', 'paper_number'],
                'indexes': [models.Index(fields=['board', 'subject_code', 'year'], name='core_offici_board_ea61ff_idx'), models.Index(fields=['is_public'], name='core_offici_is_publ_83814b_idx')],
            },
        ),
    ]
