# Generated by Django 5.0.2 on 2025-11-28 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_content_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentshare',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assessment__isnull', False), ('document__isnull', True)), models.Q(('assessment__isnull', True), ('document__isnull', False)), _connector='OR'), name='exactly_one_content_type'),
        ),
    ]
