# Generated by Django 5.0.2 on 2025-12-06 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_video_lesson_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='topic_text',
            field=models.CharField(blank=True, help_text='Legacy topic text field', max_length=200),
        ),
        migrations.AddField(
            model_name='interactivequestion',
            name='correct_option_index',
            field=models.IntegerField(blank=True, help_text='0-based index of correct MCQ option', null=True),
        ),
        migrations.AddField(
            model_name='interactivequestion',
            name='marking_guide',
            field=models.TextField(blank=True, help_text='Marking criteria for AI grading'),
        ),
        migrations.AddField(
            model_name='interactivequestion',
            name='max_marks',
            field=models.IntegerField(default=1, help_text='Maximum marks for this question'),
        ),
        migrations.AddField(
            model_name='interactivequestion',
            name='model_answer',
            field=models.TextField(blank=True, help_text='Model answer for structured/essay questions'),
        ),
        migrations.AddField(
            model_name='interactivequestion',
            name='topic_text',
            field=models.CharField(blank=True, help_text='Legacy topic text field', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='topic_text',
            field=models.CharField(blank=True, help_text='Legacy topic text field', max_length=200),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='interactivequestion',
            name='options',
            field=models.JSONField(blank=True, help_text='[{"text": "Option A", "is_correct": true}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='interactivequestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('structured', 'Structured Question'), ('essay', 'Essay/Free Response')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interactivequestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.topic'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, help_text='Syllabus year/version', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='syllabi/%Y/%m/')),
                ('external_url', models.URLField(blank=True, help_text='Link to external syllabus', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examboard')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'ordering': ['exam_board', 'subject', '-year'],
            },
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_read_count', models.IntegerField(default=0)),
                ('notes_completed', models.BooleanField(default=False)),
                ('videos_watched_count', models.IntegerField(default=0)),
                ('videos_total', models.IntegerField(default=0)),
                ('flashcards_reviewed_count', models.IntegerField(default=0)),
                ('flashcards_mastered_count', models.IntegerField(default=0)),
                ('quizzes_easy_completed', models.IntegerField(default=0)),
                ('quizzes_easy_passed', models.IntegerField(default=0)),
                ('quizzes_medium_completed', models.IntegerField(default=0)),
                ('quizzes_medium_passed', models.IntegerField(default=0)),
                ('quizzes_hard_completed', models.IntegerField(default=0)),
                ('quizzes_hard_passed', models.IntegerField(default=0)),
                ('average_quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_time_spent_minutes', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='core.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('student', 'subject', 'topic')},
            },
        ),
    ]
