# Generated by Django 5.0.2 on 2025-12-06 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_flashcard_topic_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscriptionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_subject_price', models.DecimalField(decimal_places=2, default=100.0, help_text='Price per subject (R100 default)', max_digits=10)),
                ('multi_subject_price', models.DecimalField(decimal_places=2, default=200.0, help_text='Price for 4-5 subjects (R200 default)', max_digits=10)),
                ('all_access_price', models.DecimalField(decimal_places=2, default=300.0, help_text='Price for all subjects (R300 default)', max_digits=10)),
                ('tutor_addon_price', models.DecimalField(decimal_places=2, default=500.0, help_text='Tutor email support add-on (R500 default)', max_digits=10)),
                ('per_subject_max', models.IntegerField(default=3, help_text='Max subjects for per-subject pricing')),
                ('multi_subject_min', models.IntegerField(default=4, help_text='Min subjects for multi-subject tier')),
                ('multi_subject_max', models.IntegerField(default=5, help_text='Max subjects for multi-subject tier')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Subscription Pricing',
                'verbose_name_plural': 'Student Subscription Pricing',
            },
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('per_subject', 'Per Subject (1-3)'), ('multi_subject', 'Multi Subject (4-5)'), ('all_access', 'All Access')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='free', max_length=20)),
                ('has_tutor_support', models.BooleanField(default=False)),
                ('subjects_count', models.IntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_record', to='core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupportEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('tutor', 'Tutor Help'), ('system', 'System Support'), ('billing', 'Billing Query'), ('content', 'Content Issue')], default='system', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('related_topic', models.CharField(blank=True, max_length=200)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_subject', models.ForeignKey(blank=True, help_text='Related academic subject if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_responses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_enquiries', to='core.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Support Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
