# Generated by Django 5.0.2 on 2026-01-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_crmmailinglist_crmlead_crmactivity_crmemailcampaign_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'grade', 'order', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Leave blank for topics that apply to all grades', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='core.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'grade', 'name')},
        ),
    ]
