# Generated by Django 5.0.2 on 2026-01-17 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_grade_to_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'exam_board', 'grade', 'order', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='exam_board',
            field=models.ForeignKey(blank=True, help_text='Exam board for board-specific content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.examboard'),
        ),
        migrations.AddField(
            model_name='topic',
            name='overview_text',
            field=models.TextField(blank=True, help_text='Overview/summary of what this topic covers - shown to students'),
        ),
        migrations.AddField(
            model_name='topic',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video URL for topic introduction', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'exam_board', 'grade', 'name')},
        ),
    ]
