# Generated by Django 5.0.2 on 2026-01-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_topic_examboard_overview_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.subtopic'),
        ),
    ]
