# Generated by Django 5.0.2 on 2026-01-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_subtopic_to_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolesson',
            options={'ordering': ['subject', 'topic', 'subtopic', 'order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='concept',
        ),
    ]
