# Generated by Django 5.0.2 on 2026-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_concept_from_videolesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubscriptionpricing',
            name='multi_subject_max',
        ),
        migrations.RemoveField(
            model_name='studentsubscriptionpricing',
            name='multi_subject_min',
        ),
        migrations.RemoveField(
            model_name='studentsubscriptionpricing',
            name='multi_subject_price',
        ),
        migrations.RemoveField(
            model_name='studentsubscriptionpricing',
            name='per_subject_max',
        ),
        migrations.RemoveField(
            model_name='studentsubscriptionpricing',
            name='per_subject_price',
        ),
        migrations.AddField(
            model_name='studentsubscriptionpricing',
            name='standard_boards',
            field=models.IntegerField(default=5, help_text='Max exam boards for Standard plan (any boards)'),
        ),
        migrations.AddField(
            model_name='studentsubscriptionpricing',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Standard Plan: 4 subjects, any boards (R200 default)', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentsubscriptionpricing',
            name='standard_subjects',
            field=models.IntegerField(default=4, help_text='Max subjects for Standard plan'),
        ),
        migrations.AddField(
            model_name='studentsubscriptionpricing',
            name='starter_boards',
            field=models.IntegerField(default=1, help_text='Max exam boards for Starter plan'),
        ),
        migrations.AddField(
            model_name='studentsubscriptionpricing',
            name='starter_price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Starter Plan: 2 subjects, 1 exam board (R100 default)', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentsubscriptionpricing',
            name='starter_subjects',
            field=models.IntegerField(default=2, help_text='Max subjects for Starter plan'),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter (2 subjects, 1 board)'), ('standard', 'Standard (4 subjects, any boards)'), ('all_access', 'Full Access (unlimited)')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsubscriptionpricing',
            name='all_access_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Full Access: All subjects, all boards (R500 default)', max_digits=10),
        ),
    ]
