# Generated by Django 5.0.2 on 2026-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_studentsubscriptionpricing_multi_subject_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscriptionpricing',
            name='standard_boards',
            field=models.IntegerField(default=999, help_text='Max exam boards for Standard plan (999 = any boards)'),
        ),
    ]
