# Generated by Django 5.0.2 on 2026-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_studentsubscriptionpricing_standard_boards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, default='', help_text='e.g., Grade 10, ECD A, NC, Diploma', max_length=100),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
