from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('resend-verification/', views.resend_verification, name='resend_verification'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<str:token>/', views.reset_password, name='reset_password'),
    path('account/settings/', views.account_settings, name='account_settings'),
    path('', views.dashboard_view, name='dashboard'),
    path('lesson-plans/', views.lesson_plans_view, name='lesson_plans'),
    path('classwork/', views.classwork_view, name='classwork'),
    path('homework/', views.homework_view, name='homework'),
    path('tests/', views.tests_view, name='tests'),
    path('exams/', views.exams_view, name='exams'),
    path('assignments/', views.assignments_view, name='assignments'),
    path('questions/', views.questions_view, name='questions'),
    path('documents/', views.documents_view, name='documents'),
    path('documents/upload/', views.upload_document, name='upload_document'),
    path('subscription/', views.subscription_view, name='subscription'),
    path('classes/', views.classes_view, name='classes'),
    path('classes/create/', views.create_class, name='create_class'),
    path('classes/<int:class_id>/edit/', views.edit_class, name='edit_class'),
    path('classes/<int:class_id>/delete/', views.delete_class, name='delete_class'),
    # File operations
    path('document/<int:doc_id>/delete/', views.delete_document, name='delete_document'),
    path('document/<int:doc_id>/download/', views.download_document, name='download_document'),
    path('document/<int:doc_id>/view/', views.view_document, name='view_document'),
    path('document/<int:doc_id>/inline/', views.view_document_inline, name='view_document_inline'),
    # AI generation endpoints
    path('generate-assignment/', views.generate_assignment_ai, name='generate_assignment'),
    path('generate-questions/', views.generate_questions_ai, name='generate_questions'),
    # Assignment sharing endpoints
    path('assignments/share/create/', views.create_share, name='create_share'),
    path('assignments/share/<int:share_id>/revoke/', views.revoke_share, name='revoke_share'),
    # Public access endpoints (no login required)
    path('share/a/<str:token>/', views.public_assignment_view, name='public_assignment'),
    path('share/a/<str:token>/download/', views.public_assignment_download, name='public_assignment_download'),
    # Payment and subscription endpoints
    path('subscription/dashboard/', views.subscription_dashboard, name='subscription_dashboard'),
    path('subscription/initiate/<int:plan_id>/', views.initiate_subscription, name='initiate_subscription'),
    path('payfast/notify/', views.payfast_notify, name='payfast_notify'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/cancelled/', views.payment_cancelled, name='payment_cancelled'),
    # Admin panel endpoints (using /panel/ to avoid conflict with Django's /admin/)
    path('panel/', views.admin_dashboard, name='admin_dashboard'),
    path('panel/users/', views.admin_users, name='admin_users'),
    path('panel/users/<int:user_id>/change-subscription/', views.admin_change_subscription, name='admin_change_subscription'),
    path('panel/users/<int:user_id>/toggle-status/', views.admin_toggle_user_status, name='admin_toggle_user_status'),
    path('panel/subscriptions/', views.admin_subscriptions, name='admin_subscriptions'),
    path('panel/api-test/', views.admin_api_test, name='admin_api_test'),
    path('panel/features/', views.admin_features, name='admin_features'),
    path('panel/features/exam-boards/', views.admin_exam_boards, name='admin_exam_boards'),
    path('panel/features/subjects/', views.admin_subjects, name='admin_subjects'),
    path('panel/features/grades/', views.admin_grades, name='admin_grades'),
    path('panel/features/plans/', views.admin_subscription_plans, name='admin_subscription_plans'),
    path('panel/communications/', views.admin_communications, name='admin_communications'),
    path('panel/communications/announcements/', views.admin_announcements, name='admin_announcements'),
    path('panel/communications/announcements/<int:announcement_id>/dismiss/', views.dismiss_announcement, name='dismiss_announcement'),
    path('panel/communications/emails/', views.admin_email_blasts, name='admin_email_blasts'),
    path('panel/communications/emails/send/', views.send_email_blast, name='send_email_blast'),
    # Content manager endpoints
    path('content/', views.content_dashboard, name='content_dashboard'),
    path('content/papers/', views.content_papers, name='content_papers'),
    path('content/papers/upload/', views.content_upload_paper, name='content_upload_paper'),
    path('content/papers/<int:paper_id>/reformat/', views.content_reformat_paper, name='content_reformat_paper'),
    path('content/formatted-papers/', views.content_formatted_papers, name='content_formatted_papers'),
    path('content/formatted-papers/<int:paper_id>/review/', views.content_review_formatted_paper, name='content_review_formatted_paper'),
    path('content/quizzes/', views.content_quizzes, name='content_quizzes'),
    path('content/quizzes/create/', views.content_create_quiz, name='content_create_quiz'),
    path('content/bulk-upload/', views.content_bulk_upload, name='content_bulk_upload'),
]